baseURL: "https://docs.rehive.com/"
languageCode: "en-us"
title: "Rehive documentation"
theme: hexon-hugo-theme

params:
  logoUrl: https://rehive.com
  logoImage: /images/logo.svg
  heroImage: /images/hero.svg
  favicon: /images/favicon.png

  primaryColor: "#5336FF"
  secondaryColor: "#A4A5F5"

  extraNavItems:
    - title: Sign in
      url: https://dashboard.rehive.com

  extraFooterItems:
    - title: Sign in
      url: https://dashboard.rehive.com