steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
            'build',
            '-t', '$_IMAGE-build:latest',
            '-t', '$_IMAGE-build:$TAG_NAME',
            '-f', 'etc/docker/build.Dockerfile',
            '.'
        ]
- name: 'gcr.io/cloud-builders/docker'
  args: [
            'run',
            '-v', '/workspace/public:/app/public:rw',
            '$_IMAGE-build'
        ]
- name: 'gcr.io/cloud-builders/docker'
  args: [
            'build',
            '-t', '$_IMAGE:latest',
            '-t', '$_IMAGE:$TAG_NAME',
            '-f', 'etc/docker/Dockerfile',
            '.'
        ]
images: ['$_IMAGE-build', '$_IMAGE']
